// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gin} from '../models';

export function ConnectionCreate(arg1:any):Promise<gin.H>;

export function ConnectionDelete(arg1:string):Promise<gin.H>;

export function ConnectionEdit(arg1:any):Promise<gin.H>;

export function ConnectionList():Promise<gin.H>;

export function CreateValue(arg1:any):Promise<gin.H>;

export function DbList(arg1:string):Promise<gin.H>;

export function DeleteKeyValue(arg1:any):Promise<gin.H>;

export function GetKeyValue(arg1:any):Promise<gin.H>;

export function Greet(arg1:string):Promise<string>;

export function HashAddOrUpdateField(arg1:any):Promise<gin.H>;

export function HashFieldDelete(arg1:any):Promise<gin.H>;

export function KeyList(arg1:any):Promise<gin.H>;

export function ListValueCreate(arg1:any):Promise<gin.H>;

export function ListValueDelete(arg1:any):Promise<gin.H>;

export function SendEmail(arg1:any):Promise<gin.H>;

export function SetValueCreate(arg1:any):Promise<gin.H>;

export function SetValueDelete(arg1:any):Promise<gin.H>;

export function UpdateKeyValue(arg1:any):Promise<gin.H>;

export function ZSetValueCreate(arg1:any):Promise<gin.H>;

export function ZSetValueDelete(arg1:any):Promise<gin.H>;
