// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectionCreate(arg1:any):Promise<any>;

export function ConnectionDelete(arg1:string):Promise<any>;

export function ConnectionEdit(arg1:any):Promise<any>;

export function ConnectionList():Promise<main.H>;

export function CreateValue(arg1:any):Promise<main.H>;

export function DbList(arg1:string):Promise<main.H>;

export function DeleteKeyValue(arg1:any):Promise<main.H>;

export function GetKeyValue(arg1:any):Promise<main.H>;

export function Greet(arg1:string):Promise<string>;

export function KeyList(arg1:any):Promise<main.H>;

export function UpdateKeyValue(arg1:any):Promise<main.H>;
